### ISSUE TITLE
Webpage TODO

### ISSUE THREAD

**Issue by kipkurui** [mbbu/mbbu.github.io#1]

**Comment by kipkurui** [comment]
- [x] Add background information about MBBU and the Internship Program on the landing page
- [x] Update Name of Cohorts to Bioinformatics Incubation and Mentorship Program
- [x] Add Preview to the blogs and update Titles
- [x] Create a guideline for getting blog posts from former interns
- [x] Add a tab for the Science Journey Seminar Series
- [ ]

**Comment by nanjalaruth** [comment]
Done
